=== willi84/lazy-dev/src/_data/templates/template.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["name", "version", "files", "folders", "renames"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "baseProject": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "files": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "folders": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "renames": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["from", "to"],
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== willi84/lazy-dev/src/_data/templates/sample-project.json
{
    "$schema": "./template.schema.json",
    "name": "sample-project",
    "version": "1.0.0",
    "description": "A sample project template",
    "author": "Robert Willemelis (robert.dev@gmx.de)",
    "baseProject": "sample-project",
    "source": "_tools/sample-project",
    "files": [
        "LICENSE",
        "README.md",
        "src/index.ts"
    ],
    "folders": [
        "src/_shared",
        "src/apps/api",
        "docs"
    ],
    "renames": [
        {
            "from": "sample-project",
            "to": "{{ projectName }}"
        },
        {
            "from": "2024",
            "to": "{{ currentYear }}"
        },
        {
            "from": "2025",
            "to": "{{ currentYear }}"
        },
        {
            "from": "sample-project",
            "to": "{{ projectNameNoPunctuation }}"
        }
    ]
}

=== willi84/lazy-dev/src/_data/templates/vue.json
{
    "$schema": "./template.schema.json",
    "name": "vue",
    "version": "1.0.0",
    "description": "VueJS template with TS",
    "author": "Robert Willemelis (robert.dev@gmx.de)",
    "baseProject": "pendler-alarm.de",
    "source": "2026/pendler-alarm.de",
    "files": [
        "LICENSE"
    ],
    "folders": [
        "docs"
    ],
    "renames": [
        {
            "from": "pendler-alarm.de",
            "to": "{{ projectName }}"
        },
        {
            "from": "2024",
            "to": "{{ currentYear }}"
        },
        {
            "from": "2025",
            "to": "{{ currentYear }}"
        }

    ]
}

=== willi84/lazy-dev/src/_data/templates/eleventy-nunjucks.json
{
    "$schema": "./template.schema.json",
    "name": "eleventy",
    "version": "1.0.0",
    "description": "Eleventy Nunjucks template",
    "author": "Robert Willemelis (robert.dev@gmx.de)",
    "baseProject": "daten.pm",
    "source": "2025/daten.pm",
    "files": [
        ".eleventy.shim.js",
        ".eleventyignore",
        ".gitignore",
        ".prettierrc",
        "eleventy.config.js",
        "eslint.config.cjs",
        "eslint.config.ts",
        "index.html",
        "jest.config.js",
        "jest.d.ts",
        "LICENSE",
        "package-lock.json",
        "package.json",
        "project.config.js",
        "project.config.ts",
        "README.md",
        "tsconfig.eslint.json",
        "tsconfig.json",
        "vite.config.js",
        "wallaby.js",
        "src/postcss.config.js",
        "src/_data/build.js",
        "src/_data/main.json",
        "src/backend/apps/api/index.ts",
        "src/backend/_shared/config.ts",
        "src/backend/_shared/index.d.ts",
        "src/frontend/pages/index.njk",
        "src/frontend/main.ts",
        "src/backend/config.ts",
        "src/backend/index.d.ts"
    ],
    "folders": [
        "src/backend/_shared",
        "src/backend/apps/atomic",
        "src/backend/apps/api",
        "src/backend/apps/healthcheck",
        "src/backend/apps/lint",
        "src/frontend/_framework",
        "src/frontend/assets",
        "src/frontend/components",
        "src/frontend/templates",
        "src/setup",
        "docs"
    ],
    "renames": [
        {
            "from": "daten.pm",
            "to": "{{ projectName }}"
        },
        {
            "from": "2024",
            "to": "{{ currentYear }}"
        },
        {
            "from": "2025",
            "to": "{{ currentYear }}"
        },
        {
            "from": "datenpm",
            "to": "{{ projectNameNoPunctuation }}"
        }
    ]
}
